FROM php:7.4-apache

# Copy application source
COPY . /var/www/html
COPY .docker/vhost.conf /etc/apache2/sites-available/000-default.conf
RUN chown -R www-data:www-data /app && a2enmod rewrite

#php config for MySQL
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN apt-get update -y && apt-get upgrade -y
EXPOSE 80

CMD ["start-apache"]
